### ISSUE TITLE
Callback #1 param. type int doesn't match signal spec gint

### ISSUE THREAD

**Issue by thaniyarasu** [ziutek/glib#7]
Callback #1 param. type int doesn't match signal spec gint

error raised at ubuntu 13.10 
when go install github.com/ziutek/gst

**Comment by kellydunn** [comment]
I'm also getting this issue as well when attempting to execute the live_webm example:

``` bash
$ go run live_webm.go
> panic: Callback #1 param. type int doesn't match signal spec gint

goroutine 1 [running]:
github.com/ziutek/glib.(*Object).connect(0xc2000001d8, 0x2000000001, 0x0, 0x5b7600, 0x6a5c48, ...)
    github.com/ziutek/glib/_obj/_cgo_gotypes.go:662 +0x685
github.com/ziutek/glib.(*Object).ConnectNoi(0xc2000001d8, 0x66c910, 0x11, 0x5b7600, 0x6a5c48, ...)
    github.com/ziutek/glib/_obj/_cgo_gotypes.go:722 +0x97
main.NewWebM(0x180, 0xd8, 0x19, 0x0)
    /home/kelly/work/gopath/src/github.com/ziutek/gst/examples/live_webm.go:133 +0x634
main.main()
    /home/kelly/work/gopath/src/github.com/ziutek/gst/examples/live_webm.go:144 +0x63

goroutine 2 [syscall]:

goroutine 4 [syscall]:
github.com/ziutek/glib._Cfunc_mp_wait(0x0)
    github.com/ziutek/glib/_obj/_cgo_defun.c:695 +0x2f
github.com/ziutek/glib.callbackLoop()
    github.com/ziutek/glib/_obj/_cgo_gotypes.go:856 +0x1c
created by github.com/ziutek/glib.init·1
    github.com/ziutek/glib/_obj/_cgo_gotypes.go:864 +0x1f
exit status 2

```

**Comment by ziutek** [comment]
The problem was because of wrong assumption about gint and Go int relation (works on 32-bit system, fails on 64-bit). 

I again need gst for small project with gstreamer1.0 support so gstreamer0.10 will not be supported by further commits.
